// packages/faker-ui/src/tabs/mock/mock-list.tsx
import { defineComponent, onMounted, reactive, ref } from 'vue'
import { Switch } from '../../components/ui/switch'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../components/ui/table'
import { Pagination } from '../../components/ui/pagination'
import MockEditor from './mock-editor'
import type { MockConfig, Page } from '@baicie/faker-shared'
import {
  deleteMock as apiDeleteMock,
  fetchMockList,
  updateMock,
} from '../../api'

const MockList = defineComponent({
  name: 'MockList',
  setup() {
    const mocks = ref<MockConfig[]>([])
    const loading = ref(false)
    const showEditor = ref(false)
    const currentMock = ref<any>(null)
    const search = ref('')

    const pagination = reactive({
      page: 1,
      pageSize: 10,
      itemCount: 0,
      total: 0,
    })

    async function loadMocks(params?: {
      page?: number
      pageSize?: number
      search?: string
    }) {
      loading.value = true
      try {
        const query = {
          page: params && params.page ? params.page : pagination.page,
          pageSize:
            params && params.pageSize ? params.pageSize : pagination.pageSize,
          search: params ? params.search : search.value || undefined,
        }
        const result: Page<MockConfig> = await fetchMockList(query)
        mocks.value = result.items
        pagination.total = result.pagination.total
        pagination.itemCount = result.pagination.total
        pagination.page = result.pagination.page
        pagination.pageSize = result.pagination.pageSize
      } catch (error) {
        console.error('Failed to load mocks', error)
      } finally {
        loading.value = false
      }
    }

    function handleEdit(mock: any) {
      currentMock.value = { ...mock }
      showEditor.value = true
    }

    function handleCreate() {
      currentMock.value = {
        url: '',
        method: 'GET',
        enabled: true,
        statusCode: 200,
        type: 'static',
        responseData: {},
      }
      showEditor.value = true
    }

    async function handleDelete(id: string) {
      if (!confirm('Are you sure you want to delete this Mock?')) return

      try {
        await apiDeleteMock({ id })
        loadMocks()
      } catch (error) {
        console.error('Failed to delete mock', error)
      }
    }

    async function handleToggle(id: string, enabled: boolean) {
      try {
        await updateMock({ id, updates: { enabled } })
        loadMocks()
      } catch (error) {
        console.error('Failed to toggle mock', error)
      }
    }

    function handleEditorSave(_mock: any) {
      showEditor.value = false
      loadMocks({ page: pagination.page, pageSize: pagination.pageSize })
    }

    function handleEditorCancel() {
      showEditor.value = false
      currentMock.value = null
    }

    onMounted(() => {
      loadMocks({ page: 1, pageSize: pagination.pageSize })
    })

    return () => (
      <div>
        <div class="mb-4 flex justify-between items-center gap-4">
          <div class="flex-1 max-w-sm">
            <Input
              type="text"
              placeholder="Search mocks by url, method, type..."
              modelValue={search.value}
              onUpdate:modelValue={(val: string | number) => {
                search.value = val as string
                loadMocks({ page: 1, search: search.value })
              }}
            />
          </div>
          <Button onClick={handleCreate}>Create Mock</Button>
        </div>

        <div class="rounded-lg border border-border bg-card">
          <Table class="min-w-full">
            <TableHeader>
              <TableRow>
                <TableHead class="w-[20%]">URL</TableHead>
                <TableHead class="w-[10%]">Method</TableHead>
                <TableHead class="w-[10%]">Status</TableHead>
                <TableHead class="w-[10%]">Type</TableHead>
                <TableHead class="w-[30%]">Description</TableHead>
                <TableHead class="w-[20%] text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {mocks.value.length === 0 && !loading.value ? (
                <TableRow>
                  <TableCell
                    colspan={6}
                    class="text-center text-muted-foreground h-24"
                  >
                    No mocks found
                  </TableCell>
                </TableRow>
              ) : (
                mocks.value.map(row => (
                  <TableRow key={row.id}>
                    <TableCell class="font-medium">{row.url}</TableCell>
                    <TableCell class="text-muted-foreground">
                      {row.method}
                    </TableCell>
                    <TableCell>
                      <Switch
                        modelValue={row.enabled}
                        onUpdate:modelValue={(val: boolean) =>
                          handleToggle(row.id!, val)
                        }
                      />
                    </TableCell>
                    <TableCell class="text-muted-foreground">
                      {row.type}
                    </TableCell>
                    <TableCell class="text-muted-foreground max-w-xs truncate">
                      {row.description}
                    </TableCell>
                    <TableCell class="text-right">
                      <Button
                        onClick={() => handleEdit(row)}
                        variant="link"
                        class="text-foreground hover:text-foreground underline underline-offset-4 p-0 mr-4 h-auto"
                      >
                        Edit
                      </Button>
                      <Button
                        onClick={() => handleDelete(row.id!)}
                        variant="link"
                        class="text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-300 p-0 h-auto"
                      >
                        Delete
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>

        <Pagination
          page={pagination.page}
          pageSize={pagination.pageSize}
          total={pagination.total}
          onPageChange={(page: number) => loadMocks({ page })}
        />

        {showEditor.value && (
          <MockEditor
            show={showEditor.value}
            mock={currentMock.value}
            onSave={handleEditorSave}
            onCancel={handleEditorCancel}
          />
        )}
      </div>
    )
  },
})

export default MockList

// packages/faker-ui/src/tabs/mock/mock-list.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button/index.js'
  import type { MockConfig } from '@baicie/faker-shared'
  import { fetchMockList } from '../../api/mock.js'
  import { onMount } from 'svelte'

  let mocks: any[] = $state([])
  let loading = $state(false)

  async function loadMocks() {
    loading = true
    try {
      const res = (await fetchMockList({ page: 1, pageSize: 100 })) as any
      if (res && (res.list || res.items || res.data)) {
        mocks = res.list || res.items || res.data || []
      }
    } catch (e) {
      console.error(e)
    } finally {
      loading = false
    }
  }

  onMount(() => {
    loadMocks()
  })
</script>

<div class="p-4">
  <div class="flex justify-between items-center mb-4">
    <h2 class="text-xl font-bold">Mock Configuration</h2>
    <Button size="sm">Add Mock</Button>
  </div>

  <div class="rounded-md border">
    <table class="w-full text-sm text-left">
      <thead class="bg-muted/50 text-muted-foreground">
        <tr>
          <th class="h-12 px-4 align-middle font-medium">URL</th>
          <th class="h-12 px-4 align-middle font-medium">Method</th>
          <th class="h-12 px-4 align-middle font-medium">Enabled</th>
          <th class="h-12 px-4 align-middle font-medium">Type</th>
          <th class="h-12 px-4 align-middle font-medium">Description</th>
          <th class="h-12 px-4 align-middle font-medium">Actions</th>
        </tr>
      </thead>
      <tbody>
        {#if mocks.length === 0}
          <tr>
            <td colspan="6" class="p-4 text-center text-muted-foreground">
              {#if loading}
                Loading...
              {:else}
                No mocks found
              {/if}
            </td>
          </tr>
        {:else}
          {#each mocks as mock}
            <tr class="border-t hover:bg-muted/50">
              <td class="p-4">{mock.url}</td>
              <td class="p-4">{mock.method}</td>
              <td class="p-4">{mock.enabled ? 'Yes' : 'No'}</td>
              <td class="p-4">{mock.responseType || '-'}</td>
              <td class="p-4">{mock.description || '-'}</td>
              <td class="p-4">
                <Button variant="ghost" size="sm">Edit</Button>
                <Button variant="ghost" size="sm" class="text-destructive"
                  >Delete</Button
                >
              </td>
            </tr>
          {/each}
        {/if}
      </tbody>
    </table>
  </div>
</div>
